[build]
  command = "pip install -r requirements.txt && playwright install"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.11"
  PLAYWRIGHT_BROWSERS_PATH = "0"  # This will install browsers in the default location

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
